#!/bin/bash
GENTOO_VM=openjdk-bin-21 java -jar -Xms256m -Xmx1024m -Dcom.sun.media.jai.disableMediaLib=true -Doverwrite.output=true -Dexternal.programs.home=/opt/pds-transform-tool/external-programs -jar /opt/pds-transform-tool/lib/transform-*.jar "$@"
