#!/bin/bash

# pfsconvert attempts to 'auto correct' HDR files so they look good on regular monitors
# It utlizes pfstmo_mantiuk06 (seems to produce the best looking results for photos, pfstmo_fattal02 a close runner up) filters, see: http://pfstools.sourceforge.net/man_pages.html
pfsin "$1" | pfstmo_mantiuk06 | pfsgamma -g 2.2 | pfsout "$2"
